//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfroHackReact {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AfroHackReact.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CodigoAreaInteresse]
        ///                      ,[DescricaoAreaInterese]
        ///                      ,[Ativo]
        ///                      ,[DataCadastro]
        ///                    FROM [dbo].[AreaInteresse].
        /// </summary>
        public static string AreasInteresse {
            get {
                return ResourceManager.GetString("AreasInteresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO USUARIO(
        ///                            [NomeUsuario]
        ///                           ,[CodigoTipoUsuario]
        ///                           ,[Email]
        ///                           ,[NumeroCelular]
        ///                           ,[Senha]
        ///                           ,[Ativo]
        ///                           ,[DataNascimento]
        ///                           ,[NumeroDocumento]
        ///                           ,[ExperienciaVida]
        ///                           ,[CodigoAreaInteresse]
        ///                           ,[DataCriacao])
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CriarUsuario {
            get {
                return ResourceManager.GetString("CriarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HorarioUsuarioMentor (CodigoUsuarioMentor, CodigoHorarioDisponivel, Ativo) VALUES (@Id, @CodigoHorarioDisponivel,1).
        /// </summary>
        public static string CriarUsuarioHorario {
            get {
                return ResourceManager.GetString("CriarUsuarioHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CodigoHorarioDisponivel]
        ///                      ,[DescricaoPeriodo]
        ///                      ,[DescricaoHorario]
        ///                      ,[DataInclusao]
        ///                  FROM [dbo].[HorarioDisponivel].
        /// </summary>
        public static string HorariosDisponiveis {
            get {
                return ResourceManager.GetString("HorariosDisponiveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (
        ///                        SELECT * FROM USUARIO
        ///                        JOIN HorarioUsuarioMentor ON HorarioUsuarioMentor.CodigoUsuarioMentor = USUARIO.CodigoUsuario
        ///                        WHERE
        ///                        CodigoTipoUsuario = 1
        ///                        AND HorarioUsuarioMentor.CodigoHorarioDisponivel IN
        ///                        (
        ///	                        SELECT CodigoHorarioDisponivel FROM HorarioUsuarioMentor WHERE CodigoUsuarioMentor = @CodigoUsuario
        ///                        )
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ListaMentores {
            get {
                return ResourceManager.GetString("ListaMentores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM HorarioUsuarioMentor
        ///                        JOIN HorarioDisponivel ON HorarioDisponivel.CodigoHorarioDisponivel = HorarioUsuarioMentor.CodigoHorarioDisponivel WHERE CodigoUsuarioMentor = @CodigoUsuario.
        /// </summary>
        public static string LoginHorarios {
            get {
                return ResourceManager.GetString("LoginHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///                       [CodigoUsuario]
        ///                      ,[NomeUsuario]
        ///                      ,[CodigoTipoUsuario]
        ///                      ,[Email]
        ///                      ,[NumeroCelular]
        ///                      ,[Senha]
        ///                      ,[Ativo]
        ///                      ,[DataNascimento]
        ///                      ,[NumeroDocumento]
        ///                      ,[DataCriacao]
        ///                      ,[DataAlteracao]
        ///                        FROM USUARIO WHERE EMAIL = @Email AND SENHA = @Senha.
        /// </summary>
        public static string LoginUsuario {
            get {
                return ResourceManager.GetString("LoginUsuario", resourceCulture);
            }
        }
    }
}
